### PR TITLE
Add .global.secretStore.backend in the clustergroup schema

### PR DESCRIPTION
**Pull request by mbaldessari**
It is currently not there even though we mention it in the values files.

### CODE REVIEW

**Comment by wadebee** [comment]
Looks good! 

Would it be good to also update the doc to show how turn off the vault with values-global.yaml?

---
global:
  pattern: multicloud-gitops
  secretStore:
    backend: <something-else-here>

**Review by mhjacks — APPROVED** [review]
/lgtm

**Comment by claudiol** [comment]
/lgtm
Thanks @mbaldessari!

**Review by claudiol — APPROVED** [review]
Reviewed.  Looks good to merge.

**Review by mhjacks — APPROVED** [review]

**Comment by mhjacks** [comment]
Agreed - lgtm

**Pull request merged**
