### PR TITLE
Add extra value files and nulling logic to allow "disabling" applications

### PR DESCRIPTION
**Pull request by mhjacks**

### CODE REVIEW

**Comment by mhjacks** [comment]
Some questions:
1) Do you like the "override via null" or would you prefer a "disabled: true" check like for subscriptions?
2) The ACM test is failing; is the right thing here to change the test, or is there a better way to code the helper?

Note that I've changed the Value namespace from "main" to "global" per the discussion on internal slack

**Comment by mbaldessari** [comment]
I think for consistency reasons and in order to make it more explicit I'd go for disabled

**Comment by mhjacks** [comment]
I lost the changes to ACM's helper.tpl somehow. Re-adding them

**Comment by mhjacks** [comment]
make test is passing locally:

```
Testing acm chart (naked) with opts []
PASS

Testing acm chart (industrial-edge-factory) with opts [-f values-global.yaml --set global.repoURL=https://github.com/pattern-clone/mypattern --set main.git.repoURL=https://github.com/pattern-clone/mypattern --set main.git.revision=main --set global.pattern=mypattern --set global.namespace=pattern-namespace --set global.hubClusterDomain=apps.hub.example.com --set global.localClusterDomain=apps.region.example.com --set global.clusterDomain=region.example.com --set clusterGroup.imperative.jobs[0].name=test --set clusterGroup.imperative.jobs[0].playbook=ansible/test.yml -f common/examples/industrial-edge-factory.yaml]
coalesce.go:220: warning: cannot overwrite table with non table for acm.clusterGroup.subscriptions (map[acm:map[source:redhat-operators]])
PASS

Testing acm chart (industrial-edge-hub) with opts [-f values-global.yaml --set global.repoURL=https://github.com/pattern-clone/mypattern --set main.git.repoURL=https://github.com/pattern-clone/mypattern --set main.git.revision=main --set global.pattern=mypattern --set global.namespace=pattern-namespace --set global.hubClusterDomain=apps.hub.example.com --set global.localClusterDomain=apps.region.example.com --set global.clusterDomain=region.example.com --set clusterGroup.imperative.jobs[0].name=test --set clusterGroup.imperative.jobs[0].playbook=ansible/test.yml -f common/examples/industrial-edge-hub.yaml]
PASS

Testing acm chart (medical-diagnosis-hub) with opts [-f values-global.yaml --set global.repoURL=https://github.com/pattern-clone/mypattern --set main.git.repoURL=https://github.com/pattern-clone/mypattern --set main.git.revision=main --set global.pattern=mypattern --set global.namespace=pattern-namespace --set global.hubClusterDomain=apps.hub.example.com --set global.localClusterDomain=apps.region.example.com --set global.clusterDomain=region.example.com --set clusterGroup.imperative.jobs[0].name=test --set clusterGroup.imperative.jobs[0].playbook=ansible/test.yml -f common/examples/medical-diagnosis-hub.yaml]
PASS

Testing acm chart (normal) with opts [-f values-global.yaml --set global.repoURL=https://github.com/pattern-clone/mypattern --set main.git.repoURL=https://github.com/pattern-clone/mypattern --set main.git.revision=main --set global.pattern=mypattern --set global.namespace=pattern-namespace --set global.hubClusterDomain=apps.hub.example.com --set global.localClusterDomain=apps.region.example.com --set global.clusterDomain=region.example.com --set clusterGroup.imperative.jobs[0].name=test --set clusterGroup.imperative.jobs[0].playbook=ansible/test.yml -f common/examples/values-example.yaml]
PASS
```

**Pull request merged**
